default:
  - serve

serve:
  - clean:server
  - jade
  - stylus
  - autoprefixer
  - connect:server
  - watch

build:
  - clean:build
  - jade
  - stylus
  - autoprefixer
  - copy:dist
  - useminPrepare
  - concat
  - cssmin
  # - uglify
  # - imagemin
  - svgmin
  - htmlmin
  - rev
  - usemin

clean-build:
  - clean:build
  - jade
  - stylus
  - autoprefixer
  - copy:dist
  - useminPrepare
  - concat
  - cssmin
  - uglify
  - imagemin
  - svgmin
  - htmlmin
  - usemin

publish:
  - clean:build
  - jade
  - stylus
  - autoprefixer
  - copy:dist
  - useminPrepare
  - concat
  - cssmin
  - uglify
  - imagemin
  - svgmin
  - htmlmin
  - rev
  - usemin
  - gh-pages

test:
  - clean:server
  - jade
  - stylus
  - connect:test
  - mocha

release:
  - bump-only
  - changelog
  - bump-commit

release:patch:
  - bump-only:patch
  - changelog
  - bump-commit

release:minor:
  - bump-only:minor
  - changelog
  - bump-commit

release:major:
  - bump-only:major
  - changelog
  - bump-commit
